apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multitool
  name: multitool-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
      annotations:
        k8s.v1.cni.cncf.io/networks: cattle-sriov-system/example-network-dpdk
    spec:
      containers:
      - image: praqma/network-multitool
        imagePullPolicy: Always
        name: multitool
        securityContext:
          capabilities:
            add: ["NET_ADMIN","NET_RAW", "IPC_LOCK"]
        volumeMounts:
        - mountPath: /hugepages-2Mi
          name: hugepages-2mi
        resources:
          limits:
            rancher.io/intelnicsDpdk: 1
            hugepages-2Mi: 1Gi
            memory: 2Gi
          requests:
            rancher.io/intelnicsDpdk: 1
            hugepages-2Mi: 1Gi
            memory: 2Gi
      volumes:
      - name: hugepages-2mi
        emptyDir:
          medium: HugePages-2Mi
