apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: node1-policy-dpdk
  namespace: cattle-sriov-system
spec:
  nodeSelector:
    kubernetes.io/hostname: node1
  resourceName: intelnicsDpdk
  deviceType: vfio-pci
  numVfs: 4
  mtu: 1500
  nicSelector:
    deviceID: "1528"
    vendor: "8086"
    rootDevices:
    - 0000:01:00.0
